# typed: false
# frozen_string_literal: true

# This file is auto-generated by semantic-markdown's Makefile
# To update: run `make homebrew-update TAP_DIR=/path/to/semantic-markdown-tap`
class SemanticMd < Formula
  desc "Convert HTML to clean, semantic Markdown optimized for LLMs"
  homepage "https://github.com/thorstenpfister/semantic-markdown"
  version "1.0.0"
  license "MIT"

  # This formula will be updated automatically when you run:
  # make release && make homebrew-update TAP_DIR=/path/to/semantic-markdown-tap
  #
  # The release process will:
  # 1. Build binaries for all platforms
  # 2. Create release archives
  # 3. Generate SHA256 checksums
  # 4. Update this formula with the correct URLs and checksums

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/thorstenpfister/semantic-markdown/releases/download/v1.0.0/semantic-md-v1.0.0-darwin-arm64.tar.gz"
      sha256 "PLACEHOLDER_ARM64_CHECKSUM"
    end
    if Hardware::CPU.intel?
      url "https://github.com/thorstenpfister/semantic-markdown/releases/download/v1.0.0/semantic-md-v1.0.0-darwin-amd64.tar.gz"
      sha256 "PLACEHOLDER_AMD64_CHECKSUM"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thorstenpfister/semantic-markdown/releases/download/v1.0.0/semantic-md-v1.0.0-linux-arm64.tar.gz"
      sha256 "PLACEHOLDER_LINUX_ARM64_CHECKSUM"
    end
    if Hardware::CPU.intel?
      url "https://github.com/thorstenpfister/semantic-markdown/releases/download/v1.0.0/semantic-md-v1.0.0-linux-amd64.tar.gz"
      sha256 "PLACEHOLDER_LINUX_AMD64_CHECKSUM"
    end
  end

  def install
    bin.install "semantic-md-darwin-arm64" => "semantic-md" if OS.mac? && Hardware::CPU.arm?
    bin.install "semantic-md-darwin-amd64" => "semantic-md" if OS.mac? && Hardware::CPU.intel?
    bin.install "semantic-md-linux-arm64" => "semantic-md" if OS.linux? && Hardware::CPU.arm?
    bin.install "semantic-md-linux-amd64" => "semantic-md" if OS.linux? && Hardware::CPU.intel?
  end

  test do
    assert_match "semantic-md version", shell_output("#{bin}/semantic-md version")
    html = "<h1>Test</h1><p>Content</p>"
    output = pipe_output("#{bin}/semantic-md convert", html)
    assert_match "# Test", output
  end
end
