# typed: false
# frozen_string_literal: true

# This file was generated by semantic-markdown's Makefile
class SemanticMd < Formula
  desc "Convert HTML to clean, semantic Markdown optimized for LLMs"
  homepage "https://github.com/thorstenpfister/semantic-markdown"
  version "3504153"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/thorstenpfister/semantic-markdown/releases/download/3504153/semantic-md-3504153-darwin-arm64.tar.gz"
      sha256 "2e29b8d893cb94eb78237514278aea766f894ccaf4bba1d2d8cabeca28571b98"
    end
    if Hardware::CPU.intel?
      url "https://github.com/thorstenpfister/semantic-markdown/releases/download/3504153/semantic-md-3504153-darwin-amd64.tar.gz"
      sha256 "95fae5d2723d6914a5eba1501030cbd2e2330aad39108e14e992ed541dc32af9"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thorstenpfister/semantic-markdown/releases/download/3504153/semantic-md-3504153-linux-arm64.tar.gz"
      sha256 "bf2b3f3cc0fdac9d1af1a03fec2ef151588a63dcab960a798c84aeced8bec01d"
    end
    if Hardware::CPU.intel?
      url "https://github.com/thorstenpfister/semantic-markdown/releases/download/3504153/semantic-md-3504153-linux-amd64.tar.gz"
      sha256 "9f38f4a3338d97f8ccdd2d28c621c912323c3f14fa20ad420906a882cc1fe622"
    end
  end

  def install
    bin.install "semantic-md-darwin-arm64" => "semantic-md" if OS.mac? && Hardware::CPU.arm?
    bin.install "semantic-md-darwin-amd64" => "semantic-md" if OS.mac? && Hardware::CPU.intel?
    bin.install "semantic-md-linux-arm64" => "semantic-md" if OS.linux? && Hardware::CPU.arm?
    bin.install "semantic-md-linux-amd64" => "semantic-md" if OS.linux? && Hardware::CPU.intel?
  end

  test do
    assert_match "semantic-md version", shell_output("#{bin}/semantic-md version")
    html = "<h1>Test</h1><p>Content</p>"
    output = pipe_output("#{bin}/semantic-md convert", html)
    assert_match "# Test", output
  end
end
