# typed: false
# frozen_string_literal: true

# This file was generated by semantic-markdown's Makefile
class SemanticMd < Formula
  desc "Convert HTML to clean, semantic Markdown optimized for LLMs"
  homepage "https://github.com/thorstenpfister/semantic-markdown"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/thorstenpfister/semantic-markdown/releases/download/v1.0.1/semantic-md-v1.0.1-darwin-arm64.tar.gz"
      sha256 "f6f5e4e264ac9f94aa0dd215c73d3de87cf68debd0297a99ac09b3645221e702"
    end
    if Hardware::CPU.intel?
      url "https://github.com/thorstenpfister/semantic-markdown/releases/download/v1.0.1/semantic-md-v1.0.1-darwin-amd64.tar.gz"
      sha256 "d9cda3218e34f3b65e7d9ac5fa9376688f31ffd262ccefa72d33088caf10ce46"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thorstenpfister/semantic-markdown/releases/download/v1.0.1/semantic-md-v1.0.1-linux-arm64.tar.gz"
      sha256 "1aaedb11d79a13f2660185834a7ce6c2584c2e25d26717cc01b318eac8b50ce0"
    end
    if Hardware::CPU.intel?
      url "https://github.com/thorstenpfister/semantic-markdown/releases/download/v1.0.1/semantic-md-v1.0.1-linux-amd64.tar.gz"
      sha256 "0625f18e19d2ada17502ec7e92966a490806644cb186b66947e5637172141920"
    end
  end

  def install
    bin.install "semantic-md-darwin-arm64" => "semantic-md" if OS.mac? && Hardware::CPU.arm?
    bin.install "semantic-md-darwin-amd64" => "semantic-md" if OS.mac? && Hardware::CPU.intel?
    bin.install "semantic-md-linux-arm64" => "semantic-md" if OS.linux? && Hardware::CPU.arm?
    bin.install "semantic-md-linux-amd64" => "semantic-md" if OS.linux? && Hardware::CPU.intel?
  end

  test do
    assert_match "semantic-md version", shell_output("#{bin}/semantic-md version")
    html = "<h1>Test</h1><p>Content</p>"
    output = pipe_output("#{bin}/semantic-md convert", html)
    assert_match "# Test", output
  end
end
